disabled_rules:
  - cyclomatic_complexity
  - function_body_length
  - identifier_name
  - implicit_getter
  - multiple_closures_with_trailing_closure
  - statement_position
  - todo
  - unused_optional_binding
opt_in_rules:
  - closure_spacing
  - empty_count
  - empty_string
  - explicit_init
  - legacy_cggeometry_functions
  - nimble_operator
  - number_separator
  - operator_whitespace
  - redundant_nil_coalescing
  - redundant_void_return
  - sorted_imports


